apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.werf.name }}
  annotations:
  {{ if eq .Values.werf.env "dev" }}
    # Traefik is used as ingress in k3s by default
    ingress.kubernetes.io/ssl-redirect: "false"
  {{ else }}
    kubernetes.io/ingress.class: nginx
  {{ end }}
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /graphql
            backend:
              serviceName: backend
              servicePort: 80
          - path: /
            backend:
              serviceName: frontend
              servicePort: 80